### ISSUE TITLE
Add entry point for users so they can pass own markup to be modified by Lazy Loader

### ISSUE THREAD

**Issue by florianbrinkmann** [mtoensing/lazy-loading-responsive-images#22]
When images are displayed via custom functions or `wp_get_attachment_image()`, they are not processed by Lazy Loader. I think it would be useful to have a filter or similar that lets the users pass the markup to and returns the modified lazy-load-ready markup.

**Comment by diegocanal** [comment]
Hi Florian,
Certainly this would be a huge improvement. I've had to modify several plugins for this reason to make them work with Lazy Loader.
Thanks!

**Comment by florianbrinkmann** [comment]
Solution for that comes in 4.0.0

**Comment by florianbrinkmann** [comment]
@diegocanal here is an example of how you could manually call the Lazy Loader from a theme:

```
if ( isset( $lazy_loader ) && $lazy_loader instanceof FlorianBrinkmann\LazyLoadResponsiveImages\Plugin ) {
    echo $lazy_loader->filter_markup( wp_get_attachment_image( 1261 ) );
}
```

With that, you get the result of `wp_get_attachment_image()` for the image with the ID `1261`, but with the markup modifications for the lazy loading.

Best,
Florian

**Comment by diegocanal** [comment]
Florian, thanks for the code snippet!

**Comment by diegocanal** [comment]
Hi Florian,

When images are displayed via `get_avatar()` they are not correctly processed by Lazy Loader.

Using `get_avatar()` the resulting code (following your previous example in this thread) is:

`<noscript><IMG src="https://mydomain.com/wp-content/uploads/avatar.png" width="90" height="90" alt="xxx" class="avatar avatar-90 wp-user-avatar wp-user-avatar-90 alignnone photo" sizes="90px" data-sizes="auto"></noscript>
<img src="https://mydomain.com/wp-content/uploads/avatar.png" width="90" height="90" alt="xxx" class="avatar avatar-90 wp-user-avatar wp-user-avatar-90 alignnone photo lazyautosizes ls-is-cached lazyloaded" sizes="90px" data-sizes="auto" data-src="https://mydomain.com/wp-content/uploads/avatar.png" style="">`

I can see it has been processed by Lazy Loader but not correctly. Because there is only one possible size (avatar is so small already) the `srcset` attribute is not present –which is correct–  but then `sizes="90px"` should not be included as it should only appear if there is a srcset attribute (the html won't validate).

In contrast, using wp_get_attachment_image() with the same avatar (image) is correctly processed by Lazy Loader:

`<noscript><IMG width="90" height="90" src="https://mydomain.com/wp-content/uploads/avatar.png" class="attachment-thumbnail size-thumbnail" alt="xxx"></noscript>
<img width="90" height="90" src="https://mydomain.com/wp-content/uploads/avatar.png" class="attachment-thumbnail size-thumbnail ls-is-cached lazyloaded" alt="xxx" data-src="https://mydomain.com/wp-content/uploads/avatar.png" style="">`

Clarification: I use "WP User Avatar" plugin, which disables the use of gravatars and instead allows the use of images from the media library as avatars. Nevertheless, if I deactivate it I experience the opposite (but equally wrong) result: I get the `srcset` attribute of the gravatar but without the (needed)`sizes` attribute.

I am not sure if I am missing something or if Lazy Loader might be improved to support avatars and gravatars.

The code I am using is:

```
if ( isset( $lazy_loader ) && $lazy_loader instanceof FlorianBrinkmann\LazyLoadResponsiveImages\Plugin ) {
    echo $lazy_loader->filter_markup( get_avatar( get_the_author_meta('ID'), 90 ) );
}
```

**Comment by florianbrinkmann** [comment]
Hi Diego,

thanks for reporting this, I will take a look at it!

Best,
Florian

**Comment by florianbrinkmann** [comment]
Hi Diego,

I cannot reproduce that. Do you have another plugin active that makes something with the images? Lazy Loader shouldn’t add a `sizes` attribute in any case. Only a `data-sizes`, if a `sizes` attribute is already present.

Best,
Florian

**Comment by diegocanal** [comment]
Hi Florian,

I've checked it again and the `sizes` attribute is not there anymore. It's been a while and I'm not quite sure if I changed something on my code though I would say I did. I think you can forget all I said about `get_avatar()`. Sorry for the hassle. Thank you!

**Comment by florianbrinkmann** [comment]
Hi Diego,

no problem, thanks for checking again! :)

Best,
Florian
