### ISSUE TITLE
Unite gallery problem with 5.0.0

### ISSUE THREAD

**Issue by paeno** [mtoensing/lazy-loading-responsive-images#28]
ref:
"Increased priority for the calls of the_content and post_thumbnail_html filters from 500 to 10001 to fix issues with the ShortPixel Image Optimizer. So if you use those filters and they need to run after the Lazy Loader, you need to increase the priority, too. This is the change that makes it a major version change."

Shortcode for Unitegallery (https://codecanyon.net/item/unite-gallery-wordpress-gallery-plugin/10458750) in the content of a page renders no visible content. Inspecting the output there's a `<noscript>` tag injected for each image.

On the same site, the shortcode works fine on a custom content field, and each image has no `<noscript>` tag.

Simply reverting the filter priority to 500 again in `src/Plugin.php` resolves the conflict with Unite Gallery.

**Comment by florianbrinkmann** [comment]
Hi @paeno,

thanks for opening the issue. Could you send me the plugin files so I can take a look at it if there is a solution for that? I do not want to revert the filter priority again, because as you quoted, that would break it again for another plugin.

Best,
Florian

**Comment by paeno** [comment]
Hi Florian
sorry about the late reply, and thank you for looking into this issue.
Here is the plugin files for Unite gallery:
https://www.dropbox.com/s/ae1q9sziwr5r31l/unitegallery.zip?dl=0

Best
Peder

**Comment by florianbrinkmann** [comment]
Hi Peder,

thanks. The link is not working, I guess you added a expire date(?). Could you send me a link via email to ########## (removed email after the files were sent) so there is no download link publicly visible?

Best,
Florian

**Comment by florianbrinkmann** [comment]
Hi Peder,

thanks for sending the files. I gave it a try and can reproduce it. Are you using Gutenberg? I think it should be possible to fix the issue by wrapping the shortcode into a `div` with the class `disable-lazyload`.

Otherwise, I could check if it is possible to add a new option for wrapper classnames to exclude (in that case: `unite-gallery`).

Best,
Florian

**Comment by paeno** [comment]
Hei Florian
no, not using Gutenberg yet. A new option to create custom wrapper classnames to exclude sounds like a more flexible option. The downside is that the gallery, which really would benefit from lazy load can´t use it. Is there no way to get around, fex an override I could add to my functions.php? I´m not using ShortPixel Image Optimizer, so it was working good before the update.

Best,
Peder

**Comment by florianbrinkmann** [comment]
Hi Peder,

the issue is, that the gallery directly uses the `img` elements inside the wrapper element, and the plugin adds its `noscript` elements on the same level.

> I´m not using ShortPixel Image Optimizer, so it was working good before the update.

The reason that it was working before is, that Lazy Loader ran before the Shortcode was processed, so the gallery was not lazy loaded either. So disabling the plugin via `disable-lazyload` would have the same effect like before the update.

I guess it should work, if the Unite Gallery plugin would wrap the images into a `figure` element or something like that. I do not see an easy way to get it working with my plugin. The only way would be to add the `noscript` before the gallery wrapper with the whole gallery code inside. But that is not possible with Lazy Loader, sorry…

Best,
Florian
