### ISSUE TITLE
data-no-lazyload gone

### ISSUE THREAD

**Issue by wheresrhys** [mtoensing/lazy-loading-responsive-images#9]
Hi

The feature I added a few months ago to disable lazy loading for some images https://github.com/florianbrinkmann/lazy-loading-responsive-images/commit/efc9571d35f34dbecb5b0faaee8fad1a5ee41be7 appears to have dropped out of the plugin. Could it be reinstated please

**Comment by florianbrinkmann** [comment]
Hey!

I added an option to disable lazy loading for certain images by class names (you can find it in the Customizer). Does that work for you? Or do you need an option via a `data-` attribute for some reason?

Cheers,
Florian

**Comment by wheresrhys** [comment]
well, technically it's a breaking change to remove that without a major version, so it's annoying to have to go in and update a load of templates. I would appreciate if it could be backwards compatible

**Comment by florianbrinkmann** [comment]
Oh yes, you are right with that – did not think about that, sorry. I will reinstate it and release a new version with that shortly.

**Comment by florianbrinkmann** [comment]
Could you give the master version a try if it works for you as expected? I think I removed it after reading that support thread without giving it a try myself (https://wordpress.org/support/topic/disable-lazy-load-2/ )… -.-

**Comment by wheresrhys** [comment]
I'm literally about to go on holiday. I will check it out in about a week though

**Comment by florianbrinkmann** [comment]
All right, thanks, and have a nice holiday!

**Comment by florianbrinkmann** [comment]
I just uploaded the new version 3.1.12 to the W.org repo. It works in my tests, so I will close this issue for the moment. If it should not work for you, please reopen it (just as a note: since 3.1.11 the plugin does not lazy load images which are added via `wp_get_attachment_image()`, because there is no filter I can use to add a `noscript` fallback for those images).

Thanks for the heads-up with backwards compatibility – I hope it helps me to avoid such breaking changes in the future (or at least to increase the correct version number and make it an major release) :)

And thanks at this point also from me for your PR to initially add the feature!

Cheers,
Florian
